export const WORKSPACE_LABELS: Record<string, string> = {
  RESTAURANT:        "🍔 Restaurant",
  REAL_ESTATE:       "🏠 Real Estate",
  ECOMMERCE:         "📦 Ecommerce",
  CREATOR:           "🎥 Creator",
  BUSINESS_SERVICES: "💼 Business Services",
  EVENTS:            "📢 Events",
  EDUCATION:         "🎓 Education",
  PERSONAL:          "🏡 Personal",
  FITNESS_GYM:       "💪 Fitness & Gym",
  SALON_SPA:         "💆 Salon & Spa",
  FASHION:           "👗 Fashion",
  TRAVEL:            "✈️ Travel",
  HEALTHCARE:        "🏥 Healthcare",
  AUTOMOBILE:        "🚗 Automobile",
  PHOTOGRAPHY:       "📸 Photography",
  INTERIOR_DESIGN:   "🛋️ Interior Design",
  HOTEL:             "🏨 Hotel",
  JEWELRY:           "💍 Jewelry",
};
